/*
校验目标：EAST5.0 个人信贷业务借据表（IE_005_503）GBase 存储过程草案运行后检查。
对应过程：PROC_EAST_IE_005_503_GRXDYWJJB
参数：P_DATA_DATE，格式 YYYYMMDD。
*/

-- 1. 当期行数检查
SELECT COUNT(*) AS target_count
  FROM IE_005_503
 WHERE CJRQ = ?;

-- 2. 主键/核心键重复检查（依据 DDL 注释中的 PK 字段）
SELECT CJRQ, XDJJH, COUNT(*) AS dup_cnt
  FROM IE_005_503
 WHERE CJRQ = ?
 GROUP BY CJRQ, XDJJH
HAVING COUNT(*) > 1;

-- 3. PK 字段为空检查
SELECT COUNT(*) AS null_pk_count
  FROM IE_005_503
 WHERE CJRQ = ?
   AND (CJRQ IS NULL OR XDJJH IS NULL);

-- 4. 采集日期格式检查
SELECT CJRQ, COUNT(*) AS cnt
  FROM IE_005_503
 WHERE CJRQ IS NULL OR LENGTH(CJRQ) <> 8
    OR CJRQ NOT REGEXP '^[0-9]{8}$'
 GROUP BY CJRQ;

-- 5. 日期字段格式检查（贷款发放日期、贷款到期日期、终结日期、欠本日期、欠息日期、下期还款日期）
SELECT 'DKFFRQ' AS field_name, COUNT(*) AS bad_cnt
  FROM IE_005_503
 WHERE CJRQ = ?
   AND (DKFFRQ IS NULL OR DKFFRQ NOT REGEXP '^[0-9]{8}$')
UNION ALL
SELECT 'DKDQRQ', COUNT(*)
  FROM IE_005_503
 WHERE CJRQ = ?
   AND (DKDQRQ IS NULL OR DKDQRQ NOT REGEXP '^[0-9]{8}$')
UNION ALL
SELECT 'ZJRQ', COUNT(*)
  FROM IE_005_503
 WHERE CJRQ = ?
   AND (ZJRQ IS NULL OR ZJRQ NOT REGEXP '^[0-9]{8}$')
UNION ALL
SELECT 'QBRQ', COUNT(*)
  FROM IE_005_503
 WHERE CJRQ = ?
   AND (QBRQ IS NULL OR QBRQ NOT REGEXP '^[0-9]{8}$')
UNION ALL
SELECT 'QXRQ', COUNT(*)
  FROM IE_005_503
 WHERE CJRQ = ?
   AND (QXRQ IS NULL OR QXRQ NOT REGEXP '^[0-9]{8}$')
UNION ALL
SELECT 'XQHKRQ', COUNT(*)
  FROM IE_005_503
 WHERE CJRQ = ?
   AND (XQHKRQ IS NULL OR XQHKRQ NOT REGEXP '^[0-9]{8}$');

-- 6. 码值字段检查：贷款状态（DKZT）
SELECT DKZT, COUNT(*) AS cnt
  FROM IE_005_503
 WHERE CJRQ = ?
   AND DKZT IS NOT NULL
 GROUP BY DKZT;

-- 7. 码值字段检查：贷款五级分类（DKWJFL）
SELECT DKWJFL, COUNT(*) AS cnt
  FROM IE_005_503
 WHERE CJRQ = ?
   AND DKWJFL IS NOT NULL
 GROUP BY DKWJFL;

-- 8. 码值字段检查：信贷业务种类（XDYWZL）
SELECT XDYWZL, COUNT(*) AS cnt
  FROM IE_005_503
 WHERE CJRQ = ?
   AND XDYWZL IS NOT NULL
 GROUP BY XDYWZL;

-- 9. 码值字段检查：是否互联网贷款（SFHLWDK）
SELECT SFHLWDK, COUNT(*) AS cnt
  FROM IE_005_503
 WHERE CJRQ = ?
   AND SFHLWDK IS NOT NULL
 GROUP BY SFHLWDK;

-- 10. 码值字段检查：利率类型（LLLX）
SELECT LLLX, COUNT(*) AS cnt
  FROM IE_005_503
 WHERE CJRQ = ?
   AND LLLX IS NOT NULL
 GROUP BY LLLX;

-- 11. 金额字段非负检查
SELECT 'QBJE' AS field_name, COUNT(*) AS bad_cnt
  FROM IE_005_503
 WHERE CJRQ = ? AND QBJE IS NOT NULL AND QBJE < 0
UNION ALL
SELECT 'BNQXYE', COUNT(*)
  FROM IE_005_503 WHERE CJRQ = ? AND BNQXYE IS NOT NULL AND BNQXYE < 0
UNION ALL
SELECT 'BWQXYE', COUNT(*)
  FROM IE_005_503 WHERE CJRQ = ? AND BWQXYE IS NOT NULL AND BWQXYE < 0
UNION ALL
SELECT 'DKJE', COUNT(*)
  FROM IE_005_503 WHERE CJRQ = ? AND DKJE IS NOT NULL AND DKJE < 0
UNION ALL
SELECT 'DKYE', COUNT(*)
  FROM IE_005_503 WHERE CJRQ = ? AND DKYE IS NOT NULL AND DKYE < 0
UNION ALL
SELECT 'XQYHBJ', COUNT(*)
  FROM IE_005_503 WHERE CJRQ = ? AND XQYHBJ IS NOT NULL AND XQYHBJ < 0
UNION ALL
SELECT 'XQYHLX', COUNT(*)
  FROM IE_005_503 WHERE CJRQ = ? AND XQYHLX IS NOT NULL AND XQYHLX < 0;

-- 12. 缺口字段空值检查（GSFZJG、SENSITIVEFLAG、DKRZHKHLB、KHLB 应全部为 NULL）
SELECT COUNT(*) AS gsfzjg_null_count
  FROM IE_005_503 WHERE CJRQ = ? AND GSFZJG IS NOT NULL;

SELECT COUNT(*) AS sensitive_null_count
  FROM IE_005_503 WHERE CJRQ = ? AND SENSITIVEFLAG IS NOT NULL;

SELECT COUNT(*) AS dkruzhlb_null_count
  FROM IE_005_503 WHERE CJRQ = ? AND DKRZHKHLB IS NOT NULL;

SELECT COUNT(*) AS khlb_null_count
  FROM IE_005_503 WHERE CJRQ = ? AND KHLB IS NOT NULL;

-- 13. 贷款投向行业空值检查（需求要求不可为空）
SELECT COUNT(*) AS dktxhy_null_count
  FROM IE_005_503
 WHERE CJRQ = ? AND (DKTXHY IS NULL OR TRIM(DKTXHY) = '');

-- 14. 内部机构号长度检查（从第12位截取，应至少1位）
SELECT COUNT(*) AS nbjgh_short_count
  FROM IE_005_503
 WHERE CJRQ = ? AND (NBJGH IS NULL OR LENGTH(NBJGH) = 0);

-- 15. 字段映射抽样回溯
-- TODO: 按存储过程中的来源表和业务键（T_6_27.F270001 借据ID）抽样核对源字段、目标字段和码值转换。
