-- ============================================================
-- EAST 表结构建表脚本拆分文件
-- 来源: 用户提供 eastttt.xlsx 自动生成 DDL
-- 生成时间: 2026-04-28 03:38:32
-- 拆分时间: 2026-04-28
-- 表: IE_005_503 个人信贷业务借据表
-- ============================================================

DROP TABLE IF EXISTS `IE_005_503`;
CREATE TABLE `IE_005_503` (
  `JRXKZH`                 VARCHAR(30)      DEFAULT NULL COMMENT '金融许可证号；营业机构、管理机构必须填报“金融许可证号”，内设机构、虚拟机构及营业部取本级或上一级管理机构的金融许可证号，优先取本级。',
  `KHTYBH`                 VARCHAR(70)      DEFAULT NULL COMMENT '客户统一编号；如包含个人身份证件号码，则为隐私，银行机构需做变形，变形规则见《采集技术接口说明》。关联数据项：个人基础信息表.客户统一编号',
  `MXKMMC`                 VARCHAR(300)     DEFAULT NULL COMMENT '明细科目名称；同一条数据涉及多个明细科目的，仅填报该笔业务指向的主要科目，如：一笔贷款仅包含正常本金时，填报正常本金科目，如一笔贷款既包含正常本金也包含逾期本金时，填报逾期本金科目。关联数据项：总账会计全科目表.会计科目编号。',
  `KHMC`                   VARCHAR(450)     DEFAULT NULL COMMENT '客户名称；即借款主体（最终债务人）名称，非本行开出的银行承兑汇票借款主体为开票行，非本行开出的信用证借款主体填报为开证行。关联数据项：个人基础信息表.客户姓名。隐私，银行机构变形，变形规则见《采集技术接口说明》。',
  `XDHTH`                  VARCHAR(100)     DEFAULT NULL COMMENT '信贷合同号；关联数据项：信贷合同表.信贷合同号',
  `DKFHZH`                 VARCHAR(60)      DEFAULT NULL COMMENT '贷款分户账号；个人贷款在会计系统中的记账号。关联数据项：个人信贷分户账.贷款分户账号',
  `DKFFLX`                 VARCHAR(30)      DEFAULT NULL COMMENT '贷款发放类型；票据贴现、转贴现、贸易融资、融资租赁、垫款均填报至“其他”项中。',
  `FKFS`                   VARCHAR(30)      DEFAULT NULL COMMENT '放款方式；贷款实际发放方式',
  `BZ`                     VARCHAR(3)       DEFAULT NULL COMMENT '币种',
  `DKWJFL`                 VARCHAR(6)       DEFAULT NULL COMMENT '贷款五级分类；核销、转让、结清，填报核销、转让、结清前的五级分类。与其他表格中五级分类字段一致。',
  `DQQS`                   INT              DEFAULT NULL COMMENT '当前期数；贷款目前的期数',
  `DKDQRQ`                 VARCHAR(8)       DEFAULT NULL COMMENT '贷款到期日期；贷款借据（包括展期）约定的到期日期。',
  `QBJE`                   DECIMAL(20,2)    DEFAULT NULL COMMENT '欠本金额；仅当截止报送日贷款仍为逾期状态时填报，若无欠本则填0。',
  `QBRQ`                   VARCHAR(8)       DEFAULT NULL COMMENT '欠本日期；仅当截止报送日借据仍为逾期状态时填报，如贷款人已将当期应还金额彻底还清，可以将该字段重置为默认日期。',
  `BNQXYE`                 DECIMAL(20,2)    DEFAULT NULL COMMENT '表内欠息余额；贷款表内的欠息余额，若无则填0',
  `QXRQ`                   VARCHAR(8)       DEFAULT NULL COMMENT '欠息日期；仅当截止报送日贷款仍为逾期状态时填报，如贷款人已将当期应还金额彻底还清，可以将该字段重置为默认日期。',
  `LJQKQS`                 INT              DEFAULT NULL COMMENT '累计欠款期数；在整个业务期间，已经出现过欠款的的期数的合计，不论是否连续。欠款包括欠息。',
  `DKRZZH`                 VARCHAR(60)      DEFAULT NULL COMMENT '贷款入账账号；填写贷款实际入账的账号，不可填中间过渡账户或清算账户，优先填报外部账号。票据转贴现、承兑汇票垫款、二级市场福费廷等业务填写资金转入的银行机构账号；收款人是境外机构的填写SWIFT代码；收款人是第三方平台账号的，填写第三方平台账号。',
  `GSFZJG`                 VARCHAR(200)     DEFAULT NULL COMMENT '归属分支机构',
  `SENSITIVEFLAG`          VARCHAR(30)      DEFAULT NULL COMMENT '涉密标志',
  `ZQS`                    INT              DEFAULT NULL COMMENT '总期数；贷款总期数为计划还款的总次数。',
  `ZQCS`                   INT              DEFAULT NULL COMMENT '展期次数',
  `DKRZHKHLB`              VARCHAR(6)       DEFAULT NULL COMMENT '贷款入账户客户类别',
  `LLLX`                   VARCHAR(6)       DEFAULT NULL COMMENT '利率类型',
  `HKFS`                   VARCHAR(60)      DEFAULT NULL COMMENT '还款方式；若无法以枚举类型填写，则填报“其他-XX”，XX为银行自定义类型。',
  `HKZHSSHMC`              VARCHAR(450)     DEFAULT NULL COMMENT '还款账号所属行名称；填还款账号所属行全称，收款人是第三方平台的，填写第三方平台名称。',
  `JJDKYT`                 VARCHAR(1500)    DEFAULT NULL COMMENT '借据贷款用途；填报该笔借据（放款）下资金使用的具体用途，非信贷合同贷款用途。',
  `DKTXDQ`                 VARCHAR(6)       DEFAULT NULL COMMENT '贷款投向地区；如贷款用于购房，则填报购房所在地。难以判断贷款投向地区的，填报入账账号归属地。投向多个地区的，按比重最多的地区填报。',
  `SFHLWDK`                VARCHAR(3)       DEFAULT NULL COMMENT '是否互联网贷款；是否互联网贷款的认定参照《商业银行互联网贷款管理暂行办法》。',
  `SFSNDK`                 VARCHAR(3)       DEFAULT NULL COMMENT '是否涉农贷款；涉农贷款与人民银行涉农贷款统计口径一致。',
  `SFPHXSNDK`              VARCHAR(3)       DEFAULT NULL COMMENT '是否普惠型涉农贷款；普惠性涉农贷款参照1104报表S71填报口径，包括：单户授信总额500万元（含）以下的农户经营性贷款和单户授信总额1000万元（含）以下的涉农小微企业法人贷款（含农村集体经济组织贷款、农民专业合作社贷款。',
  `SFPHXXWQYDK`            VARCHAR(3)       DEFAULT NULL COMMENT '是否普惠型小微企业贷款；普惠型小微企业贷款参照1104报表S71填报口径，包括：向小型微型企业法人、小微企业主、个体工商户发放的、用于从事生产经营活动，单户授信总额1000万元（含）以下的贷款。',
  `XDYGH`                  VARCHAR(70)      DEFAULT NULL COMMENT '信贷员工号；填写该笔信贷业务主办客户经理员工号。关联数据项：员工表.工号。',
  `BBZ`                    VARCHAR(600)     DEFAULT NULL COMMENT '备注；描述其他字段未能详尽说明的情况，或标注对本条报送记录的特殊说明（如视需要可用于说明各种不满足检核规则的例外情况：客户信息表中可标注“境外客户”“客户已工商注销”“客户名下账户均已管控”，信贷分户账中可标注“线上化业务”“自助类贷款”等）。不同备注事项用英文半角分号隔开。',
  `DKFFRQ`                 VARCHAR(8)       DEFAULT NULL COMMENT '贷款发放日期；填写贷款实际发放的日期，非贷款合同日期。',
  `KHLB`                   VARCHAR(6)       DEFAULT NULL COMMENT '客户类别',
  `RZZHSSHMC`              VARCHAR(450)     DEFAULT NULL COMMENT '入账账号所属行名称；填入账账号所属行全称，收款人是第三方平台的，填写第三方平台名称。',
  `SJLL`                   DECIMAL(20,6)    DEFAULT NULL COMMENT '实际利率；按业务实际填写，利率类型为LPR时填报最新执行利率。百分比为单位，即1/100，为年利，精确到小数点后4位。若利率为0，允许填报为0。',
  `HKZH`                   VARCHAR(60)      DEFAULT NULL COMMENT '还款账号；填写贷款当期实际还款的账号，不可填中间过渡账户或清算账户，优先填报外部账号。',
  `JXFS`                   VARCHAR(60)      DEFAULT NULL COMMENT '计息方式',
  `XQHKRQ`                 VARCHAR(8)       DEFAULT NULL COMMENT '下期还款日期；按照还款计划下期还款的日期。若本期为最后一期，还款日期填写默认值。若如计划下期还款日期的填写默认值。',
  `XQYHBJ`                 DECIMAL(20,2)    DEFAULT NULL COMMENT '下期应还本金；按照还款计划下期应还的本金总额。若本期为最后一期，还款金额可填写0。垫款填写实际应还本金总额。若无计划下期应还本金的允许为空。',
  `XQYHLX`                 DECIMAL(20,2)    DEFAULT NULL COMMENT '下期应还利息；按照还款计划下期应还的利息总额。若本期为最后一期，还款金额可填写0。垫款填写实际应还利息总额。若无计划下期应还利息的允许为空。',
  `DKTXHY`                 VARCHAR(100)     DEFAULT NULL COMMENT '贷款投向行业；与1104报表G01_VII《贷款分行业情况表》口径一致，不可为空。委托贷款也按该规则填报。',
  `SFLSDK`                 VARCHAR(3)       DEFAULT NULL COMMENT '是否绿色贷款；按照《关于绿色融资统计制度有关工作的通知》(银保监办便函[2020]739号)，填报口径与T115报表一致。',
  `SFKJDK`                 VARCHAR(3)       DEFAULT NULL COMMENT '是否科技贷款；科技金融填报口径参照1104报表S70_I《科技金融基本情况表》第II部分：科技贷款情况表。',
  `DKZT`                   VARCHAR(30)      DEFAULT NULL COMMENT '贷款状态',
  `CJRQ`                   VARCHAR(8)       DEFAULT NULL COMMENT '采集日期；PK。采集日期指该期（批次）数据报送的期末日期，例如：按日采集的表，采集日期应为每日；按月采集的表，采集日期应为月末最后一天；以此类推。有特殊报送要求的，应以报送要求的截至日期为采集日期。',
  `ZJHM`                   VARCHAR(70)      DEFAULT NULL COMMENT '证件号码；借款人证件号码。隐私，银行机构变形。变形规则见《采集技术接口说明》。',
  `XDJJH`                  VARCHAR(100)     DEFAULT NULL COMMENT '信贷借据号；PK。',
  `XDYWZL`                 VARCHAR(150)     DEFAULT NULL COMMENT '信贷业务种类；一般固定资产贷款指除了项目贷款外的固定资产贷款。个人经营性贷款不包括个人商用房贷款，消费贷款不包括住房按揭贷款、汽车贷款、助学贷款。',
  `DKJE`                   DECIMAL(20,2)    DEFAULT NULL COMMENT '贷款金额；对于贴现、福费廷业务，贷款金额填报机构实付金额。',
  `DKYE`                   DECIMAL(20,2)    DEFAULT NULL COMMENT '贷款余额；贷款账户截止到目前未还的本金余额，包括逾期未还本金，已转让/核销贷款余额为0。',
  `ZJRQ`                   VARCHAR(8)       DEFAULT NULL COMMENT '终结日期；贷款结清、核销或转让的日期，可以提前还款。若尚未终结，填报默认值。',
  `BWQXYE`                 DECIMAL(20,2)    DEFAULT NULL COMMENT '表外欠息余额；贷款表外的欠息余额，若无则填0',
  `LXQKQS`                 INT              DEFAULT NULL COMMENT '连续欠款期数；连续欠款期数，仅当截止报送日贷款仍为逾期状态时填报，填写与当前期数连续起来的欠款期数，如已归还，重置为0。',
  `SBXDJJH`                VARCHAR(100)     DEFAULT NULL COMMENT '上笔信贷借据号；当贷款发放类型为借新还旧时，此项必填。其他情况允许为空。归还的上笔借据号为多笔时，用英文半角分号隔开填报。',
  `ZJLB`                   VARCHAR(60)      DEFAULT NULL COMMENT '证件类别；借款人证件类别。',
  `DKRZHM`                 VARCHAR(450)     DEFAULT NULL COMMENT '贷款入账户名；填写贷款实际入账的户名，不可填中间过渡账户或清算账户。票据转贴现、承兑汇票垫款、二级市场福费廷业务填写交易的同业客户名称。',
  `NBJGH`                  VARCHAR(30)      DEFAULT NULL COMMENT '内部机构号；关联数据项：机构信息表.内部机构号',
  `MXKMBH`                 VARCHAR(60)      DEFAULT NULL COMMENT '明细科目编号；同一条数据涉及多个明细科目的，仅填报该笔业务指向的主要科目，如：一笔贷款仅包含正常本金时，填报正常本金科目，如一笔贷款既包含正常本金也包含逾期本金时，填报逾期本金科目。关联数据项：总账会计全科目表.会计科目编号。',
  `YHJGMC`                 VARCHAR(450)     DEFAULT NULL COMMENT '银行机构名称；需填写全称，有金融许可证号的需与金融许可证上的机构名称保持一致。关联数据项：机构信息表.银行机构名称'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='个人信贷业务借据表';
